[cerebrium.deployment]
name = "image-protection"
python_version = "3.11"
include = "[./*, main.py, cerebrium.toml]"
exclude = "[.*]"
shell_commands = []

[cerebrium.hardware]
cpu = 8
memory = 16.0
gpu_count = 1
compute = "AMPERE_A10"
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 600

[cerebrium.dependencies.pip]
transformers = "latest"
torch = ">=2.0.0"
accelerate = "latest"
safetensors = "latest"
pillow= "latest"
torchvision= "latest"
tqdm= "latest"
tensorizer = ">=2.7.0"
diffusers="latest"
pydantic="latest"
matplotlib="latest"
numpy="latest"
